# Copyright 2025 The fawa Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: fileservice
  namespace: fawa
  labels:
    app: fileservice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fileservice
  template:
    metadata:
      labels:
        app: fileservice
    spec:
      containers:
        - name: fileservice
          image: friendaa/fawa-file:0.2
          ports:
            - containerPort: 8080
          env:
            - name: CONFIG_PATH
              value: "/app/config.yaml"
            - name: MINIO_ENDPOINT
              value: "172.31.37.33:9000"
            - name: MINIO_PUBLIC_ENDPOINT
              value: "https://apifawa.marsevilspirit.com/minio"  
            - name: MINIO_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: fileservice-secrets
                  key: minio-access-key
            - name: MINIO_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: fileservice-secrets
                  key: minio-secret-key
            - name: MINIO_BUCKET_NAME
              value: "fawa"
            - name: MINIO_USE_SSL
              value: "false"
            - name: DRAGONFLY_ADDR
              value: "172.31.37.33:6379"  
          volumeMounts:
            - name: config-volume
              mountPath: /app/config.yaml
              subPath: config.yaml
      volumes:
        - name: config-volume
          configMap:
            name: fileservice-config