name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci:
    name: ci (go:${{ matrix.go-version.name }})
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          # TODO: support windows
          # - windows-latest
        go-version:
        - name: latest
          version: 1.24.x
        - name: previous
          version: 1.23.x

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version.version }}

      - name: Install just
        uses: extra-actions/setup-just@v2

      - name: Install Dependencies
        run: just tidy

      - name: lint
        run: just lint

      - name: Unit Test
        run: just test
